# Generated by Django 4.1.4 on 2022-12-24 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_user_chats'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='chats',
        ),
    ]
